image: gitlab/dind

stages:
  - build
  - docker

build-backend:
  image: gradle:7.5.1-jdk17-focal
  stage: build
  script:
    - "./gradlew build"

docker-backend:
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  stage: docker
  image: gradle:7.5.1-jdk17-focal
  services:
    - docker:dind
  script:
    - apt-get update
    - apt-get install -y apt-transport-https ca-certificates curl software-properties-common
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - apt-get update -y
    - apt-get install -y docker-ce
    - service docker start
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - export CONTAINER_FULL_IMAGE_NAME_WITH_TAG=${CI_REGISTRY_IMAGE}/bbyurl:$COMMIT_HASH
    - ./gradlew bootBuildImage --imageName="$CONTAINER_FULL_IMAGE_NAME_WITH_TAG"
    - docker push "${CI_REGISTRY_IMAGE}/bbyurl:latest"
    -     - docker run caprover/cli-caprover:v2.1.1 caprover deploy --caproverUrl $CAPROVER_URL --caproverPassword $CAPROVER_PASSWORD --caproverApp $CAPROVER_APP --imageName $CONTAINER_FULL_IMAGE_NAME_WITH_TAG