server:
  port: 18080
spring:
#  web:
#    resources:
#      static-locations:
#        - file:./src/main/resources/public/
#        - classpath:/public/
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bby
    username: bby
    password: leftfinger-rightfinger
  flyway:
    url: jdbc:postgresql://localhost:5432/bby
    user: bby
    password: leftfinger-rightfinger
bby:
  baseUrl: http://localhost:18080